#!/usr/bin/env python3

from collections import defaultdict
import sys
import re

args = sys.argv[1:]
N = int(args.pop(0))
RE_VALID_WORD = re.compile(r'^[a-z]{1,%s}$' % N)
RE_REPEATED_LETTER = re.compile(r'^.*(?P<letter>.)(?P=letter)')

freqs = defaultdict(lambda: 0)
words = []

for word in open(args.pop(0)) if args else sys.stdin:
  word = word.rstrip('\n')
  if not RE_VALID_WORD.match(word):
    continue
  if RE_REPEATED_LETTER.match(''.join(sorted(word))):
    continue
  for c in word:
    freqs[c] += 1
  words.append(word)

tiles = set(sorted(freqs.keys(), key=lambda c: freqs[c])[-N:])

print(','.join(sorted(tiles)))

for word in words:
  if not set(list(word)).difference(tiles):
    print(word)
