#!/usr/bin/env python

import sys
import re

args = sys.argv[1:]
N = int(args.pop(0))
RE_VALID_WORD = re.compile(r'^[a-z]{1,%s}$' % N)
RE_REPEATED_LETTER = re.compile(r'^.*(?P<letter>.)(?P=letter)')

words = dict((chr(ord('a')+i), set()) for i in xrange(26))

for word in file(args.pop(0)) if args else sys.stdin:
  word = word.rstrip('\n')
  if not RE_VALID_WORD.match(word):
    continue
  if RE_REPEATED_LETTER.match(''.join(sorted(word))):
    continue
  for c in word:
    words[c].add(word)

while len(words) > N:
  c = min(words.keys(), key=lambda c: len(words[c]))
  abandoned_words = words.pop(c)
  words = dict((c, words.difference(abandoned_words)) for c, words in words.items())

print ','.join(sorted(words.keys()))

for word in sorted(set().union(*words.values())):
  print word
